import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729706672443 implements MigrationInterface {
  name = "AutoGenerated1729706672443";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD \`uuid\` varchar(36) NOT NULL AFTER id`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
