import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729530446290 implements MigrationInterface {
  name = "AutoGenerated1729530446290";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`reminder\` ADD \`completed\` tinyint NOT NULL DEFAULT 0 AFTER endDate`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
