import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729698829878 implements MigrationInterface {
  name = "AutoGenerated1729698829878";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead_log\` (\`id\` int NOT NULL AUTO_INCREMENT, \`observations\` varchar(255) NOT NULL, \`leadStateId\` int NOT NULL, \`userId\` int NOT NULL, \`leadId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead_log\` ADD CONSTRAINT \`FK_544a18a5df3612290f45c4faad2\` FOREIGN KEY (\`leadStateId\`) REFERENCES \`lead_state\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`lead_log\` ADD CONSTRAINT \`FK_2ef2b699177a7c52d21761305c4\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`lead_log\` ADD CONSTRAINT \`FK_fac25518472d73eba48bb7b932d\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
