import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729700567611 implements MigrationInterface {
  name = "AutoGenerated1729700567611";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`lead\` DROP FOREIGN KEY \`FK_6b20100e1cad88eae18b78ae5ca\``
    );
    await queryRunner.query(
      `ALTER TABLE \`lead\` CHANGE \`leadStateId\` \`leadStateId\` int NULL`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD CONSTRAINT \`FK_6b20100e1cad88eae18b78ae5ca\` FOREIGN KEY (\`leadStateId\`) REFERENCES \`lead_state\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
