import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729696455094 implements MigrationInterface {
  name = "AutoGenerated1729696455094";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`group_campaign\` (\`id\` int NOT NULL AUTO_INCREMENT, \`groupId\` int NOT NULL, \`campaignId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
    await queryRunner.query(
      `ALTER TABLE \`group\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`
    );
    await queryRunner.query(
      `ALTER TABLE \`group_campaign\` ADD CONSTRAINT \`FK_a914b6faa53083c95222f2a05a0\` FOREIGN KEY (\`groupId\`) REFERENCES \`group\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`group_campaign\` ADD CONSTRAINT \`FK_2fd8ea42d9c79f0207b55abf0af\` FOREIGN KEY (\`campaignId\`) REFERENCES \`campaign\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
