import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729857632234 implements MigrationInterface {
  name = "AutoGenerated1729857632234";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`group\` CHANGE \`shift\` \`shift\` enum ('morning', 'evening', 'all') NOT NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
