import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729696747868 implements MigrationInterface {
  name = "AutoGenerated1729696747868";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`group_user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`groupId\` int NOT NULL, \`userId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`group_user\` ADD CONSTRAINT \`FK_79924246e997ad08c58819ac21d\` FOREIGN KEY (\`groupId\`) REFERENCES \`group\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`group_user\` ADD CONSTRAINT \`FK_c668a68c15f16d05c2a0102a51d\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
