import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729359293056 implements MigrationInterface {
  name = "AutoGenerated1729359293056";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`task_comment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`text\` text NOT NULL, \`documentUri\` varchar(255) NULL, \`taskId\` int NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
    await queryRunner.query(
      `ALTER TABLE \`task_comment\` ADD CONSTRAINT \`FK_0fed042ede2365de8b32e105cc6\` FOREIGN KEY (\`taskId\`) REFERENCES \`task\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`task_comment\` ADD CONSTRAINT \`FK_5e92c87acf1a8ed40db144e2bdd\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
