import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729535771874 implements MigrationInterface {
  name = "AutoGenerated1729535771874";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead_call\` (\`id\` int NOT NULL AUTO_INCREMENT, \`uuid\` varchar(36) NOT NULL, \`subject\` varchar(255) NOT NULL, \`observations\` varchar(255) NULL, \`documentUri\` varchar(255) NULL, \`contractUrl\` varchar(255) NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`completed\` tinyint NOT NULL DEFAULT 0, \`userId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead_call\` ADD CONSTRAINT \`FK_ad9785d7bc7b5db979f99f996f3\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
