import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729700797794 implements MigrationInterface {
  name = "AutoGenerated1729700797794";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`lead\` DROP FOREIGN KEY \`FK_6b20100e1cad88eae18b78ae5ca\``
    );
    await queryRunner.query(`ALTER TABLE \`user\` ADD \`leadId\` int NULL`);
    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD CONSTRAINT \`FK_6b20100e1cad88eae18b78ae5ca\` FOREIGN KEY (\`leadStateId\`) REFERENCES \`lead_state\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD CONSTRAINT \`FK_1ea8688a904adb67b64b5e5ae95\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
