import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729699902083 implements MigrationInterface {
  name = "AutoGenerated1729699902083";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead_queue\` (\`id\` int NOT NULL AUTO_INCREMENT, \`leadId\` int NOT NULL, \`userId\` int NOT NULL, \`position\` int UNSIGNED NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead_queue\` ADD CONSTRAINT \`FK_6f7acbae008121d23dc179e16e7\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`lead_queue\` ADD CONSTRAINT \`FK_e45518fa133db5350509aebc597\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
