import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729358213886 implements MigrationInterface {
  name = "AutoGenerated1729358213886";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`task_state\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`colorHex\` varchar(10) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    //Pre populate values
    await queryRunner.query(
      `INSERT INTO \`task_state\` (\`name\`, \`colorHex\`) VALUES ('Por Hacer', '#57a9de'), ('Haciendo', '#f9d02d'), ('Hecho', '#7ede57'), ('Falta Info', '#ee4d3a')`
    );

    await queryRunner.query(
      `CREATE TABLE \`task\` (\`id\` int NOT NULL AUTO_INCREMENT, \`uuid\` varchar(36) NOT NULL, \`subject\` varchar(255) NOT NULL, \`startDate\` date NOT NULL, \`assigneeUserId\` int NOT NULL, \`creatorUserId\` int NOT NULL, \`taskStateId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
    await queryRunner.query(
      `ALTER TABLE \`task\` ADD CONSTRAINT \`FK_50c206f95df8094b5c3f6781377\` FOREIGN KEY (\`assigneeUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`task\` ADD CONSTRAINT \`FK_cc6fdd3fe4f9cc5358818629bf6\` FOREIGN KEY (\`creatorUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`task\` ADD CONSTRAINT \`FK_7cd01e1e30375516e5215c1417b\` FOREIGN KEY (\`taskStateId\`) REFERENCES \`task_state\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
