import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729695538671 implements MigrationInterface {
  name = "AutoGenerated1729695538671";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`campaign\` (\`id\` int NOT NULL AUTO_INCREMENT, \`uuid\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('Automatic', 'Manual') NOT NULL, \`sector\` enum ('Luz', 'Gas', 'Placas', 'Telefonia') NOT NULL, \`source\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
