import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729436293689 implements MigrationInterface {
  name = "AutoGenerated1729436293689";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`notification\` ADD \`startDate\` date NOT NULL AFTER userId`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
