import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729695913051 implements MigrationInterface {
  name = "AutoGenerated1729695913051";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`group\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`description\` text NULL, \`shift\` enum ('morning', 'evening') NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
