import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729362062955 implements MigrationInterface {
  name = "AutoGenerated1729362062955";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`task\` DROP FOREIGN KEY \`FK_7cd01e1e30375516e5215c1417b\``
    );
    await queryRunner.query(
      `ALTER TABLE \`task\` CHANGE \`taskStateId\` \`taskStateId\` int NOT NULL DEFAULT '1'`
    );
    await queryRunner.query(
      `ALTER TABLE \`task\` ADD CONSTRAINT \`FK_7cd01e1e30375516e5215c1417b\` FOREIGN KEY (\`taskStateId\`) REFERENCES \`task_state\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
