import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729706812450 implements MigrationInterface {
  name = "AutoGenerated1729706812450";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO \`lead_state\` (\`name\`, \`colorHex\`) VALUES ('Venta', '#89ea3d'), ('Agenda Personal', '#fbdd34'),
       ('Por la mañana', '#2fdfed'), ('Por la tarde', '#2fdfed'), ('Agendar a compañero', '#2fdfed'), ('No contesta', '#f7931c'),
       ('No interesa', '#f7511c'), ('No se puede mejorar', '#f7511c'), ('Erroneo', '#f7511c'), ('Ilocalizable', '#f7511c')`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
