import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729708905759 implements MigrationInterface {
  name = "AutoGenerated1729708905759";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`group\` ADD \`uuid\` varchar(36) NOT NULL AFTER id`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
