import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729697035260 implements MigrationInterface {
  name = "AutoGenerated1729697035260";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead_state\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`colorHex\` varchar(10) NOT NULL, UNIQUE INDEX \`IDX_bf1dd1b3a688908f6d078f8daf\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
