import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729706376502 implements MigrationInterface {
  name = "AutoGenerated1729706376502";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_1ea8688a904adb67b64b5e5ae95\``
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_1ea8688a904adb67b64b5e5ae9\` (\`leadId\`)`
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX \`REL_1ea8688a904adb67b64b5e5ae9\` ON \`user\` (\`leadId\`)`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD CONSTRAINT \`FK_1ea8688a904adb67b64b5e5ae95\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
