import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729697545857 implements MigrationInterface {
  name = "AutoGenerated1729697545857";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead\` (\`id\` int NOT NULL AUTO_INCREMENT, \`fullName\` varchar(255) NOT NULL, \`phoneNumber\` varchar(15) NOT NULL, \`email\` varchar(100) NULL, \`billUri\` varchar(255) NULL, \`shift\` enum ('morning', 'evening') NULL, \`leadStateId\` int NOT NULL, \`campaignId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD CONSTRAINT \`FK_6b20100e1cad88eae18b78ae5ca\` FOREIGN KEY (\`leadStateId\`) REFERENCES \`lead_state\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD CONSTRAINT \`FK_e87c2c99970d86ddf8c149a2d96\` FOREIGN KEY (\`campaignId\`) REFERENCES \`campaign\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
