import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1729438533770 implements MigrationInterface {
  name = "AutoGenerated1729438533770";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`agent_user_visible_user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`agentId\` int NOT NULL, \`visibleUserId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`agent_user_visible_user\` ADD CONSTRAINT \`FK_1a11bcc2e7c03da24559fff1da9\` FOREIGN KEY (\`visibleUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
