import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1730206059486 implements MigrationInterface {
  name = "AutoGenerated1730206059486";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`campaign\` CHANGE \`type\` \`type\` enum ('Automatic', 'Manual') NOT NULL DEFAULT 'Automatic'`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
