import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1730203283091 implements MigrationInterface {
  name = "AutoGenerated1730203283091";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`campaign\` CHANGE \`sector\` \`sector\` enum ('Luz', 'Gas', 'Placas', 'Telefonia') NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
