import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1730131964658 implements MigrationInterface {
  name = "AutoGenerated1730131964658";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `INSERT INTO \`lead_state\` (\`name\`, \`colorHex\`) VALUES ('Duplicado', '#f7511c')`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
