import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1732809516059 implements MigrationInterface {
  name = "AutoGenerated1732809516059";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`leadPriorities\` text NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
