import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1732560967318 implements MigrationInterface {
  name = "AutoGenerated1732560967318";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`imageUri\` varchar(255) NULL AFTER isManager`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
