import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1732609007507 implements MigrationInterface {
  name = "AutoGenerated1732609007507";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`user_contract_preference\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`columns\` text NOT NULL, UNIQUE INDEX \`REL_18ea0db65e35d914bdbef082b3\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`user_contract_preference\` ADD CONSTRAINT \`FK_18ea0db65e35d914bdbef082b30\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
