import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733590441592 implements MigrationInterface {
  name = "AutoGenerated1733590441592";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`user_share_lead\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`visibleShareLeadUserId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`user_share_lead\` ADD CONSTRAINT \`FK_37abdcaeb41e75653ea2e4961be\` FOREIGN KEY (\`visibleShareLeadUserId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
