import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733832834957 implements MigrationInterface {
  name = "AutoGenerated1733832834957";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`lead_call\` ADD \`leadId\` int NULL`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead_call\` ADD CONSTRAINT \`FK_4babe2149824ea9d8b164d00163\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
