import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733155541988 implements MigrationInterface {
  name = "AutoGenerated1733155541988";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`origin\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL, \`extraInfo\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` ADD \`originId\` int NULL AFTER tradeName`
    );

    await queryRunner.query(
      `ALTER TABLE \`customer\` ADD CONSTRAINT \`FK_f2ad0b742b20122a487bc3dae1d\` FOREIGN KEY (\`originId\`) REFERENCES \`origin\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
