import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733387145232 implements MigrationInterface {
  name = "AutoGenerated1733387145232";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD \`type\` enum ('2.0', '3.0', '6.1') NOT NULL AFTER surplusSlot1`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
