import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733140725449 implements MigrationInterface {
  name = "AutoGenerated1733140725449";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`notification\` CHANGE \`eventType\` \`eventType\` enum ('task', 'reminder', 'leadCall', 'communication') NOT NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
