import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733141705574 implements MigrationInterface {
  name = "AutoGenerated1733141705574";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`notification\` ADD \`documentUri\` varchar(255) NULL`
    );

    await queryRunner.query(
      `ALTER TABLE \`notification\` ADD \`subject\` varchar(120) NULL AFTER eventType`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
