import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1733129069286 implements MigrationInterface {
  name = "AutoGenerated1733129069286";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`customer\` ADD \`zipCode\` varchar(20) NOT NULL AFTER address`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` ADD \`province\` varchar(100) NOT NULL AFTER zipCode`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` ADD \`populace\` varchar(100) NOT NULL AFTER province`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
