import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734538232354 implements MigrationInterface {
  name = "AutoGenerated1734538232354";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`notification\` CHANGE \`eventType\` \`eventType\` enum ('task', 'reminder', 'leadCall', 'communication', 'other') NOT NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
