import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734372898761 implements MigrationInterface {
  name = "AutoGenerated1734372898761";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_Channel_Contract\``
    );

    await queryRunner.query(
      `ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_710b254675d05694ccdf5ebcf55\` FOREIGN KEY (\`channelId\`) REFERENCES \`channel\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
