import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734373234066 implements MigrationInterface {
  name = "AutoGenerated1734373234066";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_User_Contract\``
    );

    await queryRunner.query(
      `ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_a837a077c734b8f4106c6923685\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
