import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734442715713 implements MigrationInterface {
  name = "AutoGenerated1734442715713";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD \`assignedUserName\` varchar(255) NULL AFTER shift`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
