import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734358529730 implements MigrationInterface {
  name = "AutoGenerated1734358529730";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD \`paymentMoney\` float NULL AFTER paymentDay`
    );
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD \`paymentPoints\` float NULL AFTER paymentMoney`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
