import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734008521027 implements MigrationInterface {
  name = "AutoGenerated1734008521027";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead_sheet\` (\`id\` int NOT NULL AUTO_INCREMENT, \`uuid\` varchar(36) NOT NULL, \`name\` varchar(100) NOT NULL, \`surnames\` varchar(100) NOT NULL, \`nationalId\` varchar(20) NOT NULL, \`email\` varchar(100) NOT NULL, \`address\` varchar(255) NOT NULL, \`zipCode\` varchar(20) NOT NULL, \`province\` varchar(100) NOT NULL, \`populace\` varchar(100) NOT NULL, \`phoneNumber\` varchar(15) NOT NULL, \`iban\` varchar(40) NOT NULL, \`holderChange\` tinyint NOT NULL DEFAULT 0, \`newCreation\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('B2C', 'B2B') NOT NULL, \`cif\` varchar(20) NULL, \`tradeName\` varchar(100) NULL, \`leadId\` int NULL, UNIQUE INDEX \`REL_3d43c69cffbe06fec783e6c0f7\` (\`leadId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`lead_sheet\` ADD CONSTRAINT \`FK_3d43c69cffbe06fec783e6c0f71\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
