import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734537505298 implements MigrationInterface {
  name = "AutoGenerated1734537505298";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`notificationsPreferences\` text NULL AFTER leadPriorities`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
