import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734370507382 implements MigrationInterface {
  name = "AutoGenerated1734370507382";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD \`documentation\` text NULL AFTER surplusSlot1`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
