import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734546239579 implements MigrationInterface {
  name = "AutoGenerated1734546239579";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD \`renewable\` tinyint NOT NULL DEFAULT 0 AFTER documentation`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
