import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734457326080 implements MigrationInterface {
  name = "AutoGenerated1734457326080";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`reminder\` DROP COLUMN \`endDate\``);
    await queryRunner.query(
      `ALTER TABLE \`lead_call\` DROP COLUMN \`endDate\``
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
