import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734372575978 implements MigrationInterface {
  name = "AutoGenerated1734372575978";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` DROP FOREIGN KEY \`FK_Channel\``
    );

    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD CONSTRAINT \`FK_7b1f87a4c73822f1e2e4721637c\` FOREIGN KEY (\`channelId\`) REFERENCES \`channel\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
