import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1734088159203 implements MigrationInterface {
  name = "AutoGenerated1734088159203";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD \`paymentDay\` int NULL AFTER renewDays`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
