import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1735405234422 implements MigrationInterface {
  name = "AutoGenerated1735405234422";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`name\` \`name\` varchar(100) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`surnames\` \`surnames\` varchar(100) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`nationalId\` \`nationalId\` varchar(20) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`email\` \`email\` varchar(100) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`address\` \`address\` varchar(255) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`zipCode\` \`zipCode\` varchar(20) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`province\` \`province\` varchar(100) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`populace\` \`populace\` varchar(100) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(15) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`iban\` \`iban\` varchar(40) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`holderChange\` \`holderChange\` tinyint NOT NULL DEFAULT 0`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`newCreation\` \`newCreation\` tinyint NOT NULL DEFAULT 0`
    );
    await queryRunner.query(
      `ALTER TABLE \`customer\` CHANGE \`type\` \`type\` enum ('B2C', 'B2B') NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
