import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1735409998558 implements MigrationInterface {
  name = "AutoGenerated1735409998558";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user_contract_preference\` DROP FOREIGN KEY \`FK_18ea0db65e35d914bdbef082b30\``
    );

    await queryRunner.query(
      `ALTER TABLE \`user_contract_preference\` ADD CONSTRAINT \`FK_18ea0db65e35d914bdbef082b30\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
