import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1735565663531 implements MigrationInterface {
  name = "AutoGenerated1735565663531";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_Company_Contract\``
    );
    await queryRunner.query(
      `ALTER TABLE \`contract\` DROP FOREIGN KEY \`FK_Rate_Contract\``
    );
    await queryRunner.query(
      `ALTER TABLE \`contract\` CHANGE \`companyId\` \`companyId\` int NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`contract\` CHANGE \`rateId\` \`rateId\` int NULL`
    );

    await queryRunner.query(
      `ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_936abe955fb4bf453631ba04de9\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`contract\` ADD CONSTRAINT \`FK_f87704aea3af4e8fdabba011735\` FOREIGN KEY (\`rateId\`) REFERENCES \`rate\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
