import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1735471457746 implements MigrationInterface {
  name = "AutoGenerated1735471457746";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`contract\` CHANGE \`cups\` \`cups\` varchar(30) NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
