import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1735235382982 implements MigrationInterface {
  name = "AutoGenerated1735235382982";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`task_comment\` DROP FOREIGN KEY \`FK_5e92c87acf1a8ed40db144e2bdd\``
    );

    await queryRunner.query(
      `ALTER TABLE \`task_comment\` ADD CONSTRAINT \`FK_5e92c87acf1a8ed40db144e2bdd\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
