import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1735469164451 implements MigrationInterface {
  name = "AutoGenerated1735469164451";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`notification\` MODIFY COLUMN \`startDate\` datetime NOT NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
