import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1737025568965 implements MigrationInterface {
  name = "AutoGenerated1737025568965";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`contract_state\` ADD \`default\` tinyint NOT NULL DEFAULT 0`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
