import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1737819138183 implements MigrationInterface {
  name = "AutoGenerated1737819138183";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`rate\` CHANGE \`type\` \`type\` enum ('2.0', '3.0', '6.1') NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
