import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1737811489906 implements MigrationInterface {
  name = "AutoGenerated1737811489906";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`company\` CHANGE \`type\` \`type\` enum ('Luz', 'Gas', 'Telefonía') NOT NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`contract\` CHANGE \`type\` \`type\` enum ('Luz', 'Gas', 'Telefonía') NOT NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
