import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1738231393050 implements MigrationInterface {
  name = "AutoGenerated1738231393050";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`telephony_data\` DROP COLUMN \`extraServices\``);
    await queryRunner.query(`ALTER TABLE \`telephony_data\` ADD \`extraServices\` json NULL`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
