import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1743154959447 implements MigrationInterface {
    name = 'AutoGenerated1743154959447'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`customer\` ADD \`nationality\` varchar(100) NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`customer\` DROP COLUMN \`nationality\``);
    }

}
