import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1743585874527 implements MigrationInterface {
    name = 'AutoGenerated1743585874527'

    public async up(queryRunner: QueryRunner): Promise<void> {  
        await queryRunner.query(`CREATE TABLE \`contract_comment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`text\` text NOT NULL, \`documentUri\` varchar(255) NULL, \`contractId\` int NOT NULL, \`userId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`contract_comment\` ADD CONSTRAINT \`FK_15bfcb8f8de8a202405bbf5ffa8\` FOREIGN KEY (\`contractId\`) REFERENCES \`contract\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_comment\` ADD CONSTRAINT \`FK_bd1dbb40c91363227e67cdd8b9b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {}

}
