import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1745944774379 implements MigrationInterface {
  name = "AutoGenerated1745944774379";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`start_date\` date NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`days\` varchar(10) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`time\` varchar(20) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`shift\` enum ('mañana', 'tarde') NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`phone\` varchar(20) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`iban\` varchar(34) NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
