import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1745938894384 implements MigrationInterface {
    name = 'AutoGenerated1745938894384'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`payroll\` (\`id\` int NOT NULL AUTO_INCREMENT, \`uuid\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`state\` enum ('Pendiente', 'Pagada') NOT NULL DEFAULT 'Pendiente', \`qty\` decimal(10,2) NOT NULL, \`date\` date NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`payroll\` ADD CONSTRAINT \`FK_542f3c5e009e4502f7c308f33c7\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        
    }

}
