import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1745320310521 implements MigrationInterface {
    name = 'AutoGenerated1745320310521'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`notification\` ADD \`notified\` tinyint NOT NULL DEFAULT 0 AFTER \`read\``);
        await queryRunner.query(`UPDATE \`notification\` SET \`notified\` = 1`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
