import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1746788557998 implements MigrationInterface {
  name = "AutoGenerated1746788557998";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`holidays\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` date NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
