import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1746012264205 implements MigrationInterface {
  name = "AutoGenerated1746012264205";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`days\``);
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`days\` varchar(30) NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
