import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1746654995305 implements MigrationInterface {
    name = 'AutoGenerated1746654995305'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`payroll\` CHANGE \`state\` \`state\` enum ('pendiente', 'pagada') NOT NULL DEFAULT 'pendiente'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        
    }

}
