import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1746747519642 implements MigrationInterface {
  name = "AutoGenerated1746747519642";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`absences\` (\`id\` int NOT NULL AUTO_INCREMENT, \`uuid\` varchar(36) NOT NULL, \`userId\` int NOT NULL, \`startDate\` date NOT NULL, \`endDate\` date NOT NULL, \`type\` enum ('vacaciones', 'asuntos_propios', 'baja_medica', 'otro') NOT NULL DEFAULT 'vacaciones', \`description\` text NULL, \`status\` enum ('pendiente', 'aprobada', 'rechazada') NOT NULL DEFAULT 'pendiente', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b5b8e527c7998c761a3c3a3b71\` (\`uuid\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
