import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1746004987260 implements MigrationInterface {
    name = 'AutoGenerated1746004987260'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`notificationsEmailPreferences\` text NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
