import { MigrationInterface, QueryRunner, TableColumn } from "typeorm";

export class AutoGenerated1747823359695 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`user_document\` (
                \`id\` int NOT NULL AUTO_INCREMENT,
                \`uuid\` varchar(36) NOT NULL,
                \`userId\` int NOT NULL,
                \`documentUri\` varchar(255) NOT NULL,
                \`originalName\` varchar(255) NOT NULL,
                \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
                INDEX \`IDX_user_document_uuid\` (\`uuid\`),
                PRIMARY KEY (\`id\`)
            ) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`user_document\` 
             ADD CONSTRAINT \`FK_user_document_userId\` 
             FOREIGN KEY (\`userId\`) 
             REFERENCES \`user\`(\`id\`) 
             ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user_document\` DROP FOREIGN KEY \`FK_user_document_userId\``
    );
    await queryRunner.query(`DROP TABLE \`user_document\``);
  }
}
