import { MigrationInterface, QueryRunner, TableColumn } from "typeorm";

export class AutoGenerated1747823359675 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      "contract",
      "contractStateId",
      new TableColumn({
        name: "contractStateId",
        type: "int",
        isNullable: true,
        default: undefined,
      })
    );

    await queryRunner.query(`
        UPDATE \`contract\`
        SET \`contractStateId\` = NULL
        WHERE \`isDraft\` = 1 AND \`contractStateId\` = 3
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.changeColumn(
      "contract",
      "contractStateId",
      new TableColumn({
        name: "contractStateId",
        type: "int",
        isNullable: false,
        default: "1",
      })
    );

    await queryRunner.query(`
        UPDATE \`contract\`
        SET \`contractStateId\` = 3
        WHERE \`isDraft\` = 1 AND \`contractStateId\` IS NULL
    `);
  }
}
