import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1747670488841 implements MigrationInterface {
  name = "AutoGenerated1747670488841";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE UNIQUE INDEX \`IDX_3faf6c491629c8de6f0d632f60\` ON \`commission_assignment\` (\`channelId\`, \`rateId\`, \`userId\`)`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
