import { MigrationInterface, QueryRunner, Table, TableColumn, TableForeignKey } from "typeorm";

export class AutoGenerated1747823359899 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`lead_document\` (
                \`id\` int NOT NULL AUTO_INCREMENT, 
                \`uuid\` varchar(36) NOT NULL, 
                \`leadId\` int NOT NULL, 
                \`documentUri\` varchar(255) NOT NULL, 
                \`originalName\` varchar(255) NOT NULL, 
                \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
                INDEX \`IDX_lead_document_uuid\` (\`uuid\`), 
                PRIMARY KEY (\`id\`), 
                CONSTRAINT \`FK_lead_document_leadId\` FOREIGN KEY (\`leadId\`) REFERENCES \`lead\`(\`id\`) ON DELETE CASCADE
            ) ENGINE=InnoDB`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
