import { MigrationInterface, QueryRunner, TableColumn, TableForeignKey } from "typeorm";

export class AutoGenerated1747823359699 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
        const table = await queryRunner.getTable("lead");
        const foreignKey = table.foreignKeys.find(fk => fk.columnNames.indexOf("campaignId") !== -1);
        if (foreignKey) {
            await queryRunner.dropForeignKey("lead", foreignKey);
        }

        await queryRunner.query(`ALTER TABLE \`lead\` MODIFY COLUMN \`campaignId\` int NULL`);
        
        await queryRunner.createForeignKey("lead", new TableForeignKey({
            columnNames: ["campaignId"],
            referencedColumnNames: ["id"],
            referencedTableName: "campaign",
            onDelete: "SET NULL",
            onUpdate: "CASCADE"
        }));
    }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
