import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1747665221744 implements MigrationInterface {
  name = "AutoGenerated1747665221744";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`commission_assignment\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` int NOT NULL, \`channelId\` int NULL, \`rateId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`
    );
    await queryRunner.query(
      `ALTER TABLE \`commission_assignment\` ADD CONSTRAINT \`FK_c545cd337e04aaca4e7ea98d68d\` FOREIGN KEY (\`channelId\`) REFERENCES \`channel\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`commission_assignment\` ADD CONSTRAINT \`FK_73069cdc83f0b2d8e885e2d5fab\` FOREIGN KEY (\`rateId\`) REFERENCES \`rate\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`commission_assignment\` ADD CONSTRAINT \`FK_4ef68361e098b85ea6e1f1f95bb\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`
    );
    await queryRunner.query(
      `ALTER TABLE \`rate\` ADD CONSTRAINT \`FK_361637ba99ad0443186ea9baa2b\` FOREIGN KEY (\`companyId\`) REFERENCES \`company\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
