import { MigrationInterface, QueryRunner, TableColumn } from "typeorm";

export class AutoGenerated1747823359697 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`user_liquidation_preference\` (
                \`id\` int NOT NULL AUTO_INCREMENT,
                \`userId\` int NOT NULL UNIQUE,
                \`columns\` text NOT NULL,
                PRIMARY KEY (\`id\`)
            ) ENGINE=InnoDB`
    );

    await queryRunner.query(
      `ALTER TABLE \`user_liquidation_preference\` 
             ADD CONSTRAINT \`FK_user_liquidation_preference_userId\` 
             FOREIGN KEY (\`userId\`) 
             REFERENCES \`user\`(\`id\`) 
             ON DELETE CASCADE ON UPDATE NO ACTION`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user_liquidation_preference\` DROP FOREIGN KEY \`FK_user_liquidation_preference_userId\``
    );
    await queryRunner.query(`DROP TABLE \`user_liquidation_preference\``);
  }
}
