import { MigrationInterface, QueryRunner, TableColumn, TableForeignKey } from "typeorm";

export class AutoGenerated1747823359799 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`lead\` ADD \`removedCampaignName\` varchar(255) NULL AFTER assignedUserName`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`lead\` DROP COLUMN \`removedCampaignName\``);
  }
}
