import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1750430099033 implements MigrationInterface {
    name = 'AutoGenerated1750430099033'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`notification\` ADD \`creatorId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notification\` ADD CONSTRAINT \`FK_dd9610f49f6281c705287cf8e67\` FOREIGN KEY (\`creatorId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
