import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1750346212039 implements MigrationInterface {
  name = "AutoGenerated1750346212039";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`address\` varchar(255) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`user\` ADD \`cif\` varchar(50) NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
