import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1750345017086 implements MigrationInterface {
  name = "AutoGenerated1750345017086";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`channel\` ADD \`address\` varchar(255) NULL`
    );
    await queryRunner.query(
      `ALTER TABLE \`channel\` ADD \`cif\` varchar(50) NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
