import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1750430099038 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {

        await queryRunner.query(`ALTER TABLE \`notification\` ADD \`batchId\` varchar(36) NOT NULL AFTER uuid`);
        
        await queryRunner.query(`CREATE INDEX \`IDX_notification_batchId\` ON \`notification\` (\`batchId\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_notification_batchId\` ON \`notification\``);
        
        await queryRunner.query(`ALTER TABLE \`notification\` DROP COLUMN \`batchId\``);
    }

}
