import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1750081634652 implements MigrationInterface {
  name = "AutoGenerated1750081634652";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`task\` DROP COLUMN \`startDate\``);
    await queryRunner.query(
      `ALTER TABLE \`task\` ADD \`startDate\` timestamp NOT NULL`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
