import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1750346212042 implements MigrationInterface {
  name = "AutoGenerated1750346212042";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`channel\` ADD \`iban\` varchar(255) NULL AFTER cif`
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
